### ISSUE TITLE
-p / --pretty should imply --json

### ISSUE THREAD

**Issue by paleite** [pichillilorenzo/deps-report#1]
# What happens
Running `deps-report -p find-dependencies *.js` yields the regular output

# What's expected
The output should be JSON. The help text says `-p, --pretty Pretty-print JSON output (implies --json)`.

**Comment by pichillilorenzo** [comment]
With `Pretty-print JSON output (implies --json)` I mean that you need to use `-jp` together. You can't use only `-p` because it will have no effect to the output!
